#!/usr/bin/env python3
"""
OWID Commons File Categorizer

This script automatically adds country-specific categories to OWID graph files on Wikimedia Commons.
It reads JSON files generated by Phase 1 and adds categories in the format:
    Category:Our World in Data graphs of {Country}

Requirements:
- Python 3.10+
- mwclient library
- python-dotenv library
- Valid Wikimedia Commons bot credentials in .env file
"""

import json
import logging
import os
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional

import mwclient
from dotenv import load_dotenv


# Configuration
COUNTRIES_DIR = Path("output/countries")
LOG_DIR = Path("logs")
LOG_FILE = LOG_DIR / "categorize_commons.log"

# User-Agent header (required by Wikimedia)
USER_AGENT = "OWID-Commons-Categorizer/1.0 (https://github.com/MrIbrahem/OWID-categories; contact via GitHub)"

# Rate limiting: delay between edits in seconds
EDIT_DELAY = 1.5


def setup_logging():
    """Set up logging configuration."""
    LOG_DIR.mkdir(exist_ok=True)
    
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[
            logging.FileHandler(LOG_FILE),
            logging.StreamHandler(sys.stdout)
        ]
    )


def load_credentials() -> tuple[Optional[str], Optional[str]]:
    """
    Load credentials from .env file.
    
    Returns:
        Tuple of (username, password) or (None, None) if not found
    """
    load_dotenv()
    username = os.getenv("USERNAME")
    password = os.getenv("PASSWORD")
    
    if not username or not password:
        logging.error("USERNAME and/or PASSWORD not found in .env file")
        return None, None
    
    return username, password


def connect_to_commons(username: str, password: str) -> Optional[mwclient.Site]:
    """
    Connect to Wikimedia Commons using mwclient.
    
    Args:
        username: Bot username
        password: Bot password
        
    Returns:
        Connected Site object or None on failure
    """
    try:
        logging.info("Connecting to Wikimedia Commons...")
        site = mwclient.Site("commons.wikimedia.org", clients_useragent=USER_AGENT)
        
        logging.info(f"Logging in as {username}...")
        site.login(username, password)
        
        logging.info("Successfully connected and logged in")
        return site
        
    except Exception as e:
        logging.error(f"Failed to connect to Commons: {e}")
        return None


def build_category_name(country: str) -> str:
    """
    Build the category name for a country.
    
    Args:
        country: Country name (e.g., "Canada")
        
    Returns:
        Category name (e.g., "Category:Our World in Data graphs of Canada")
    """
    return f"Category:Our World in Data graphs of {country}"


def get_page_text(site: mwclient.Site, title: str) -> Optional[str]:
    """
    Get the current text content of a page.
    
    Args:
        site: Connected mwclient Site
        title: Page title
        
    Returns:
        Page text or None if page doesn't exist
    """
    try:
        page = site.pages[title]
        if page.exists:
            return page.text()
        return None
    except Exception as e:
        logging.error(f"Error getting page text for {title}: {e}")
        return None


def category_exists_on_page(page_text: str, category: str) -> bool:
    """
    Check if a category already exists on a page.
    
    Args:
        page_text: Current page text
        category: Category name to check (e.g., "Category:Our World in Data graphs of Canada")
        
    Returns:
        True if category exists, False otherwise
    """
    if not page_text:
        return False
    
    # Check for various category formats
    # [[Category:Name]] or [[category:Name]]
    category_simple = category.replace("Category:", "")
    
    checks = [
        f"[[{category}]]",
        f"[[{category.lower()}]]",
        f"[[Category:{category_simple}]]",
        f"[[category:{category_simple}]]",
    ]
    
    return any(check in page_text for check in checks)


def add_category_to_page(
    site: mwclient.Site,
    title: str,
    category: str,
    dry_run: bool = False
) -> bool:
    """
    Add a category to a page on Commons.
    
    Args:
        site: Connected mwclient Site
        title: Page title (e.g., "File:Agriculture share gdp, 1997 to 2021, CAN.svg")
        category: Category to add (e.g., "Category:Our World in Data graphs of Canada")
        dry_run: If True, don't actually make the edit
        
    Returns:
        True if category was added (or would be added in dry-run), False otherwise
    """
    try:
        page = site.pages[title]
        
        if not page.exists:
            logging.warning(f"Page does not exist: {title}")
            return False
        
        # Get current page text
        current_text = page.text()
        
        # Check if category already exists
        if category_exists_on_page(current_text, category):
            logging.info(f"Category already exists on {title}")
            return False
        
        # Add category at the end of the page
        new_text = current_text.rstrip() + f"\n[[{category}]]\n"
        
        if dry_run:
            logging.info(f"[DRY RUN] Would add '{category}' to {title}")
            return True
        
        # Make the edit
        edit_summary = f"Add {category} (automated)"
        page.save(new_text, summary=edit_summary)
        
        logging.info(f"Successfully added '{category}' to {title}")
        return True
        
    except Exception as e:
        logging.error(f"Error adding category to {title}: {e}")
        return False


def load_country_json(file_path: Path) -> Optional[Dict]:
    """
    Load a country JSON file.
    
    Args:
        file_path: Path to the JSON file
        
    Returns:
        Parsed JSON data or None on error
    """
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        logging.error(f"Error loading {file_path}: {e}")
        return None


def process_country_file(
    site: mwclient.Site,
    file_path: Path,
    dry_run: bool = False,
    graphs_only: bool = True
) -> Dict[str, int]:
    """
    Process a single country JSON file and add categories to its files.
    
    Args:
        site: Connected mwclient Site
        file_path: Path to country JSON file
        dry_run: If True, don't actually make edits
        graphs_only: If True, only process graph files (not maps)
        
    Returns:
        Dictionary with statistics (added, skipped, errors)
    """
    stats = {
        "added": 0,
        "skipped": 0,
        "errors": 0
    }
    
    # Load country data
    data = load_country_json(file_path)
    if not data:
        stats["errors"] += 1
        return stats
    
    iso3 = data.get("iso3")
    country = data.get("country")
    graphs = data.get("graphs", [])
    
    if not country:
        logging.error(f"No country name in {file_path}")
        stats["errors"] += 1
        return stats
    
    # Build category name
    category = build_category_name(country)
    
    logging.info(f"\nProcessing {iso3} ({country}): {len(graphs)} graphs")
    
    # Process graphs
    for graph in graphs:
        title = graph.get("title")
        if not title:
            logging.warning(f"Graph missing title in {file_path}")
            stats["errors"] += 1
            continue
        
        # Add category
        if add_category_to_page(site, title, category, dry_run):
            stats["added"] += 1
        else:
            stats["skipped"] += 1
        
        # Rate limiting
        if not dry_run:
            time.sleep(EDIT_DELAY)
    
    return stats


def main(dry_run: bool = False, limit: Optional[int] = None):
    """
    Main execution function.
    
    Processes graph files (not maps) from country JSON files and adds country-specific
    categories to them on Wikimedia Commons.
    
    Args:
        dry_run: If True, don't actually make edits
        limit: Optional limit on number of countries to process
    """
    setup_logging()
    
    logging.info("=" * 80)
    logging.info("OWID Commons File Categorizer")
    logging.info("=" * 80)
    
    if dry_run:
        logging.info("Running in DRY RUN mode - no actual edits will be made")
    
    # Load credentials
    username, password = load_credentials()
    if not username or not password:
        logging.error("Failed to load credentials from .env file")
        logging.error("Please create a .env file with USERNAME and PASSWORD")
        sys.exit(1)
    
    # Connect to Commons
    site = connect_to_commons(username, password)
    if not site:
        logging.error("Failed to connect to Wikimedia Commons")
        sys.exit(1)
    
    # Check if countries directory exists
    if not COUNTRIES_DIR.exists():
        logging.error(f"Countries directory not found: {COUNTRIES_DIR}")
        logging.error("Please run Phase 1 (fetch_commons_files.py) first")
        sys.exit(1)
    
    # Get all country JSON files
    country_files = sorted(COUNTRIES_DIR.glob("*.json"))
    
    if not country_files:
        logging.error(f"No country JSON files found in {COUNTRIES_DIR}")
        sys.exit(1)
    
    logging.info(f"Found {len(country_files)} country files")
    
    # Apply limit if specified
    if limit:
        country_files = country_files[:limit]
        logging.info(f"Processing limited to first {limit} countries")
    
    # Process each country file
    total_stats = {
        "added": 0,
        "skipped": 0,
        "errors": 0,
        "countries_processed": 0
    }
    
    for file_path in country_files:
        stats = process_country_file(site, file_path, dry_run)
        total_stats["added"] += stats["added"]
        total_stats["skipped"] += stats["skipped"]
        total_stats["errors"] += stats["errors"]
        total_stats["countries_processed"] += 1
    
    # Final summary
    logging.info("\n" + "=" * 80)
    logging.info("FINAL SUMMARY")
    logging.info("=" * 80)
    logging.info(f"Countries processed: {total_stats['countries_processed']}")
    logging.info(f"Categories added: {total_stats['added']}")
    logging.info(f"Already had category (skipped): {total_stats['skipped']}")
    logging.info(f"Errors: {total_stats['errors']}")
    logging.info("=" * 80)
    
    if dry_run:
        logging.info("\nThis was a DRY RUN - no actual edits were made")
        logging.info("Run without --dry-run flag to make actual edits")


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Add country categories to OWID graph files on Wikimedia Commons"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Run in dry-run mode (no actual edits)"
    )
    parser.add_argument(
        "--limit",
        type=int,
        help="Limit processing to first N countries (for testing)"
    )
    
    args = parser.parse_args()
    
    try:
        main(dry_run=args.dry_run, limit=args.limit)
    except KeyboardInterrupt:
        logging.info("\nInterrupted by user")
        sys.exit(0)
    except Exception as e:
        logging.error(f"Fatal error: {e}", exc_info=True)
        sys.exit(1)
