#!/usr/bin/env python3
"""
OWID Commons Countries/Continents Categorizer

This script automatically adds country/continent-specific categories to OWID graph files on Wikimedia Commons.
It reads JSON files generated by Phase 1 and adds categories in the format:
    Category:Our World in Data graphs of {Country}
    Category:Our World in Data graphs of {Continent}

Requirements:
- Python 3.10+
- mwclient library
- python-dotenv library
- Valid Wikimedia Commons bot credentials in .env file

Usage:
    python run_categorize.py                                            # Process all countries
    python run_categorize.py --dry-run                                  # Test without making edits
    python run_categorize.py --limit 5                                  # Process first 5 countries only
    python run_categorize.py --files-per-item 10                        # Process 10 files per country
    python run_categorize.py --work-path continents --files-type maps   # Process continents and maps
    python run_categorize.py --work-path continents --files-type maps --dry-run --files-per-item 1
"""

import argparse
import logging

from main_app.main_run_categorize import run_categories_entry
from main_app.owid_config import LOG_FILE_CONTINENTS, LOG_FILE_COUNTRIES
from main_app.logger_config import setup_logging

logger = logging.getLogger(__name__)

setup_logging(
    level="INFO",
    name="main_app",
    log_file=str(LOG_FILE_CONTINENTS),
    use_colorlog=False,
    overwrite=True,
)

def main() -> None:

    parser = argparse.ArgumentParser(description="Add categories to OWID graph files on Wikimedia Commons")
    parser.add_argument("--dry-run", action="store_true", help="Run in dry-run mode (no actual edits)")
    parser.add_argument("--limit", type=int, help="Limit processing to first N items (for testing)")
    parser.add_argument(
        "--files-per-item", type=int, help="Limit processing to N files per country/continent (for testing)"
    )
    # add work_path argument
    parser.add_argument(
        "--work-path",
        choices=["countries", "continents"],
        default="countries",
        help="Specify whether to process 'countries' or 'continents' (default: countries)",
    )
    # add files_type argument
    parser.add_argument(
        "--files-type",
        choices=["graphs", "maps"],
        default="graphs",
        help="Specify whether to process 'graphs' or 'maps' (default: graphs)",
    )
    args = parser.parse_args()

    run_categories_entry(
        dry_run=args.dry_run,
        limit=args.limit,
        files_per_one=args.files_per_item,
        work_path=args.work_path,
        files_type=args.files_type,
    )


if __name__ == "__main__":
    main()
